name: Comprehensive R CMD check + BiocCheck

on:
  workflow_dispatch:

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  pkg-at-root:
    name: Root Pkg - Bioc ${{ matrix.bioc-version }} (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, windows-2022, windows-2025, macos-14, macos-15]
        ## Test using both Bioconductor devel and release
        bioc-version: [devel, release]

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Build jvecfor JAR
        if: runner.os != 'Windows'
        run: make install

      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@devel
        with:
          bioc-version: ${{ matrix.bioc-version }}
          bioc-mirror: https://ftp.gwdg.de/pub/misc/bioconductor
          use-public-rspm: true

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1

      - name: Build, Install, Check
        id: build-install-check
        uses: grimbough/bioc-actions/build-install-check@devel
        with:
          package-directory: '.'

      ## Turn off the checks that we know will fail
      ## Cause the workflow to error if any new errors appear
      - name: Run BiocCheck with arguments
        uses: grimbough/bioc-actions/run-BiocCheck@devel
        with:
          package-directory: '.'
          arguments: '--no-check-bioc-views --no-check-vignettes --no-check-bioc-help'
          error-on: 'error'

      ## upload the Rcheck folder regardless of success of failure
      - name: Upload output
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.os }}-bioc-${{ matrix.bioc-version}}-Rcheck
          path: |
            ${{ steps.build-install-check.outputs.check-dir }}

      ## upload source and binary packages
      - name: Upload check output
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-bioc-${{ matrix.bioc-version}}-pkgs
          path: |
            ${{ steps.build-install-check.outputs.source-tarball }}
            ${{ steps.build-install-check.outputs.package-binary }}


      - name: Upload install log if that step fails
        if: always() && (steps.build-install-check.outcome == 'failure')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-bioc-${{ matrix.bioc-version}}-install_log
          path: |
            ${{ steps.build-install-check.outputs.install-log }}

  using-bioc-docker:
    name: Docker Devel
    strategy:
      fail-fast: false
      matrix:
        ## Test using both Bioconductor devel and release
        bioc-version: [devel, RELEASE_3_22]

    runs-on: ubuntu-22.04
    container: bioconductor/bioconductor_docker:${{ matrix.bioc-version }}

    steps:

      - uses: actions/checkout@v4

      ##################################################
      ## no need to install R, BiocManager, or Pandoc ##
      ##################################################

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Build jvecfor JAR
        run: make install

      ## cache installed packages
      - name: Cache install R packages
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/R/site-library
          key: docker-1
          restore-keys: docker-

      ## we can use BiocManager to install binary packages in the Docker container
      - name: Install dependencies
        run: |
            BiocManager::install(c('BiocParallel', 'Matrix', 'bluster', 'data.table',
                                   'BiocNeighbors', 'BiocStyle', 'igraph',
                                   'knitr', 'rmarkdown', 'testthat'))
        shell: Rscript {0}

      - name: Build, Install, Check
        id: build-install-check
        uses: grimbough/bioc-actions/build-install-check@devel
        with:
          package-directory: '.'

      ## Turn off the checks that we know will fail
      ## Cause the workflow to error if any new errors appear
      - name: Run BiocCheck with arguments
        uses: grimbough/bioc-actions/run-BiocCheck@devel
        with:
          package-directory: '.'
          arguments: '--no-check-bioc-views --no-check-vignettes --no-check-bioc-help'
          error-on: 'error'

      - name: Upload built package binary
        uses: actions/upload-artifact@v4
        with:
          name: docker-bioc-${{ matrix.bioc-version }}-binary
          path: |
            ${{ steps.build-install-check.outputs.package-binary }}

      - name: Upload install log if that step fails
        if: always() && (steps.build-install-check.outcome == 'failure')
        uses: actions/upload-artifact@v4
        with:
          name: docker-bioc-${{ matrix.bioc-version }}-install-log
          path: |
            ${{ steps.build-install-check.outputs.install-log }}
